---
title: "manuscript"
format: html
editor: visual
---

## Abstract

## Introduction

## Methods

Two sets of experiments were conducted. In the first, the volume of water filtered and filter pore size varied while the preservation and extraction methods remained constant. This experiment also used homogenized source water to reduce true biological variability in samples and specifically measure the effect of the difference in volume filtered and filter pore size. The second set of experiments held volume filtered and filter pore size constant while varying the type of preservation and the extraction method. Here, source water was not homogenized and true biological variability (i.e., bottle to bottle variation) is included. 

After DNA extraction, all extracts from both experiments followed the same procedures for total DNA quantification, assessment for inhibition, and quantification of target DNA via quantitative PCR (qPCR).  

### Field sampling, filtration, preservation, extraction 

#### Pore size and volume comparison

Water samples were collected from Hood Canal near Bangor, Washington in September 2022 from a netted pen containing three Atlantic bottlenose dolphins (*Tursiops truncatus*) (\*CHECK WITH BANGOR). A total of X L of water was collected on site in X large, clean carboys. Water was transported from the sampling site to the NOAA Northwest Fisheries Science Center (NWFSC) (on ice?), which took approximately 3 hours (check!). 

At the lab, carboys were well mixed to homogenize the source water before splitting it into individual samples. Samples were assigned to a volume filtered treatment (1 L or 3 L) and a pore size treatment (1 um or 5 um), for a total of four treatments, each with three biological replicates (i.e., filters). All filters were 47 mm diameter mixed cellulose ester (MCE; \*add manufacturer) and water was filtered using a vacuum manifold and sterile, single use filter funnels. After filtration, filters were removed with sterile forceps and placed into 5 ml (check) tubes with 2 ml (check) of Longmire's buffer (cite longmires here) and stored at room temperature for 1 month (check) until DNA extraction. All filters were extracted using a protocol for phenol-chlorofom-isoamyl with a phase lock (see Ramon-Laca 2021 for detailed protocol - CITE https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0257773). Total DNA of all extracts were quantified via a Qubit fluorometer.

#### Preservation and extraction comparison 

For the samples where volume filtered and pore size were held constant but preservation and extraction varied, water was collected from a closed pen with recirculating water and a filtration system with one dolphin inside the pen at the time of sampling (\*CHECK WITH BANGOR). Water samples were filtered on site *in situ* using a Smith Root Citizen Science sampler (cite). For each water sample, 3 L of water was filtered onto a 5 um pore size 47 mm diameter MCE self-preserving Smith Root filter (cite Austen's paper). A total of X filters were collected over a time period of approximately 1 hour. The self-preserving filters were transported back to NOAA NWFSC within approximately 3 hours (check). At the lab, samples were randomized across the time of collection to various treatments of preservation (n = 5 total; RNALater, Longmire's, -80C freezer, self-preserving at room temperature, and Zymo DNA/RNA Shield) and extraction method (n = 3 total; phenol-chloroform-isoamyl, Qiagen Blood and Tissue Kit, Zymo Mini Prep Kit). Some preservation methods were incompatible with some extraction methods, resulting in not a full factorial design but 13 combinations of the two treatments. 

All samples were preserved for X weeks (about a month?) before being extracted. For samples extracted via the same phenol-chloroform-isoamyl method as the volume filtered and pore size experiment, all five preservation methods were tested. For samples extracted via the Qiagen Blood and Tissue Kit, all preservation methods except Longmire's buffer were tested. For samples extracted via the Zymo Mini Prep Kit, all preservation methods except RNALater were tested. Total DNA of all extracts were quantified via a Qubit fluorometer.

### Inhibition testing and target DNA quantification 

All samples run in triplicate and were assessed for inhibition by using an internal positive control (IPC) assay that was multiplexed with the target DNA assay by utilizing two different reporters. The IPC assay used was TaqMan Exogenous Internal Positive Control Reagents (EXO-IPC) (Applied Biosystems, USA). The IPC was included in all environmental samples and also in no template controls (NTC). Samples were deemed inhibited if the difference in mean Ct value of the IPC measured in the sample and the mean Ct value of the IPC measured in the sample was greater than 0.5. Inhibited samples were diluted and re-run until the difference in Ct was less than 0.5.  

Target DNA (*T. tursiops*) was quantified using an assay targeting a 80 base pair fragment of the Cytochrome B gene (\* MEG CHECK; ALSO ASSAY NOT PUBLISHED) using a synthetic gBlock (IDT) as a standard curve from 100,000 copies/ul to 1 copy/ul in a ten-fold dilution series. The final recipe and cycling conditions for the assay are found in Supplemental Text 1. 

\* MEG TO CHECK DETAILS 

### Quantifying the impact of methods on inhibiton 

Model for inhibition 

### Optimizing the target to total DNA ratio 



## Results

The two sets of experiments used different source water, 

### Inhibition



### Total DNA, target DNA, target:total DNA ratios 




## Discussion

