---
title: "Needle in Haystack, Sweet Spot, Listen to Megan"
author:
  -Elizabeth Andruszkiewicz Allan
  -Megan R. Shaffer
  -Ryan P. Kelly
  -Kim Parsons
format:
  pdf:
    fig_caption: yes
    keep_tex: yes
    latex_engine: pdflatex
    number_sections: no
    extra_dependencies: float
bibliography: references.bib
csl: ecological-applications.csl
---
\newpage 

## Abstract

There are many choices that simply must be made when sampling for eDNA analysis, whether a targeted, single-species approach or a community-based, metabarcoding approach. Of the entire workflow from sampling water to bioinformatic analyses, it seems like the choices in molecular methods and downstream bioinformatics are the most important. However, the first steps in the process of collecting water, filtering it, and preserving it are also important and are often overlooked as major decision points. Many researchers use established methods with limited or no testing for their particular research question. Here, we investigate (1) the volume of water filtered and the filter pore size and (2) the preservation method and extraction method of samples with a specific lens on how inhibition and rarity of target interact with these choices to impact the detection of a single targeted assay (via qPCR and ddPCR) and community compositions (via metabarcoding). We find that XXX filtering larger volumes and maximizing total DNA yield during extraction is not always beneficial to detection likely due to the concentration of inhibitors and co-extraction of off-target template. We recommend collecting pilot samples to determine the minimum volume of water required given the rarity of the target and using an extraction method tailored to the taxa of interest. Finally, we note that inhibition is often masked in metabarcoding read proportions and recommend quantifying inhibition in environmental samples before metabarcoding to avoid missing rare taxa or misinterpreting proportions of target taxa. 

The number of studies utilizing information from environmental DNA (eDNA) from water samples has and continues to increase at a steady rate. Whether looking for a specific species' DNA or looking for many species via metabarcoding, the first step of any project includes making many decisions about collecting samples. Namely, the volume of water to filter, filter pore size, preservation, and extraction methods all must be chosen before embarking on a project. Though previous work has investigated the impacts of these choices on target DNA capture, here we expand upon how these choices affect not only target DNA capture, but how they also impact inhibition and target:total DNA recovery. We compared two different filtration volumes (1 L vs. 3 L) and two pore size filters (1 um vs. 3 um) for the same preservation and extraction method. We then compared five preservation methods (RNALater, Longmire's buffer, -80C, Smith Root self preserving filters, and DNA/RNA Shield) and three extraction methods (phenol-chloroform-isoamyl, Qiagen Blood and Tissue, Zymo Mini Prep) while holding the volume filtered and pore size constant. We found that collecting more water on a larger filter pore size maximized target DNA and the target:total DNA ratio. We also found that concentrating larger volumes of water concentrates more inhibitors. 

\newpage

## Introduction

The first few steps to designing a sampling protocol for eDNA require researchers to make many decisions. These include things like: where should I take my sample, what depth should I sample at, how much volume should I filter, what pore size filter should I use, and many others. After water collection and filtration, 

In an ideal world, sampling would minimize effort, minimize the concentration of inhibitors, maximize target DNA capture, and maximize the ratio of target:total DNA. 

In reality, in order to maximize target DNA, the logical first step is to filter more water. Though this will increase target DNA, it will also increase both total DNA and inhibitors. With increased concentration of total DNA and inhibitors, the extraction and detection of target might be negatively impacted. For example, if a sample is more inhibited, it may require dilution or cleaning.  

Therefore, more water might not always be better. 

## Methods

Two sets of experiments were conducted. In the first, the volume of water filtered and filter pore size varied while the preservation and extraction methods remained constant. This experiment also used homogenized source water to reduce true biological variability in samples and specifically measure the effect of the difference in volume filtered and filter pore size. The second set of experiments held volume filtered and filter pore size constant while varying the type of preservation and the extraction method. Here, source water was not homogenized and true biological variability (i.e., bottle to bottle variation) is included.

After DNA extraction, all extracts from both experiments followed the same procedures for total DNA quantification, assessment for inhibition, and quantification of target DNA via quantitative PCR (qPCR).

### Field sampling, filtration, preservation, extraction

#### Pore size and volume comparison

Water samples were collected from Hood Canal near Bangor, Washington in September 2022 from a netted pen containing three Atlantic bottlenose dolphins (*Tursiops truncatus*) (\*CHECK WITH BANGOR). A total of X L of water was collected on site in X large, clean carboys. Water was transported from the sampling site to the NOAA Northwest Fisheries Science Center (NWFSC) (on ice?), which took approximately 3 hours (check!).

At the lab, carboys were well mixed to homogenize the source water before splitting it into individual samples. Samples were assigned to a volume filtered treatment (1 L or 3 L) and a pore size treatment (1 um or 5 um), for a total of four treatments, each with three biological replicates (i.e., filters). All filters were 47 mm diameter mixed cellulose ester (MCE; \*add manufacturer) and water was filtered using a vacuum manifold and sterile, single use filter funnels. After filtration, filters were removed with sterile forceps and placed into 5 ml (check) tubes with 2 ml (check) of Longmire's buffer (cite longmires here) and stored at room temperature for 1 month (check) until DNA extraction. All filters were extracted using a protocol for phenol-chlorofom-isoamyl with a phase lock (see Ramon-Laca 2021 for detailed protocol [@ramón-laca2021]). Total DNA of all extracts were quantified via a Qubit fluorometer.

#### Preservation and extraction comparison

For the samples where volume filtered and pore size were held constant but preservation and extraction varied, water was collected from a closed pen with recirculating water and a filtration system with one dolphin inside the pen at the time of sampling (\*CHECK WITH BANGOR). Water samples were filtered on site *in situ* using a Smith Root Citizen Science sampler (cite). For each water sample, 3 L of water was filtered onto a 5 um pore size 47 mm diameter MCE self-preserving Smith Root filter (cite Austen's paper). A total of X filters were collected over a time period of approximately 1 hour. The self-preserving filters were transported back to NOAA NWFSC within approximately 3 hours (check). At the lab, samples were randomized across the time of collection to various treatments of preservation (n = 5 total; RNALater, Longmire's, -80C freezer, self-preserving at room temperature, and Zymo DNA/RNA Shield) and extraction method (n = 3 total; phenol-chloroform-isoamyl, Qiagen Blood and Tissue Kit, Zymo Mini Prep Kit). Some preservation methods were incompatible with some extraction methods, resulting in not a full factorial design but 13 combinations of the two treatments.

All samples were preserved for X weeks (about a month?) before being extracted. For samples extracted via the same phenol-chloroform-isoamyl method as the volume filtered and pore size experiment, all five preservation methods were tested. For samples extracted via the Qiagen Blood and Tissue Kit, all preservation methods except Longmire's buffer were tested. For samples extracted via the Zymo Mini Prep Kit, all preservation methods except RNALater were tested. Total DNA of all extracts were quantified via a Qubit fluorometer.

### Inhibition testing and target DNA quantification

* Meg to check - one set (either pore size/vol filtered or preservation/extraction had the 1:10 dilution run through clean up kit)

All samples run in triplicate and were assessed for inhibition by using an internal positive control (IPC) assay that was multiplexed with the target DNA assay by utilizing two different reporters. The IPC assay used was TaqMan Exogenous Internal Positive Control Reagents (EXO-IPC) (Applied Biosystems, USA). The IPC was included in all environmental samples and also in no template controls (NTC). Samples were deemed inhibited if the difference in mean Ct value of the IPC measured in the sample and the mean Ct value of the IPC measured in the sample was greater than 0.5. Inhibited samples were diluted and re-run until the difference in Ct was less than 0.5.

Target DNA (*T. tursiops*) was quantified using an assay targeting a 80 base pair fragment of the Cytochrome B gene (\* MEG CHECK; ALSO ASSAY NOT PUBLISHED) using a synthetic gBlock (IDT) as a standard curve from 100,000 copies/ul to 1 copy/ul in a ten-fold dilution series. The final recipe and cycling conditions for the assay are found in Supplemental Text 1.

\* MEG TO CHECK DETAILS

### Quantifying the impact of methods on inhibiton

Model for inhibition

### Optimizing the target to total DNA ratio

## Results

The two sets of experiments used different source water,

### Inhibition

### Total DNA, target DNA, target:total DNA ratios

## Discussion

\newpage  

## References